site_name: Curso de Python GIS
theme:
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  

site_url: "https://255ribeiro.github.io/curso_python_gis/"
repo_url: "https://github.com/255ribeiro/curso_python_gis/"
repo_name: "255ribeiro/curso_python_gis" 

nav:
  - Home: index.md
  - Instalação do Python: intro_py\instala.md
  - Primeiros Passos com o Python: intro_py\intro_py.md
  - Programação Científica com o Python:
      - numpy: cientif_py\numpy.md
      - scipy: cientif_py\scipy.md
      - matplotlib: cientif_py\plt.md
      - Jupyter notebooks: cientif_py\jupyter_intro.ipynb
  - Manipulação de dados:
      - pandas: dados_py/pandas.md
  - Dados geoespaciais:
    - Geopandas: geo_py/geopandas.md
  - Referências: ref/ref.md

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 3

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter:
      include_source: True