site_name: Curso de Python GIS
use_directory_urls: false

copyright: Copyright &copy; 2016 - 2021 Fernando Ferraz Ribeiro

theme:
  features:

    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      #primary: orange
      #accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  

site_url: "https://255ribeiro.github.io/curso_python_gis/"
repo_url: "https://github.com/255ribeiro/curso_python_gis/"
repo_name: "255ribeiro/curso_python_gis" 

nav:
  - Home: index.md
  - Instalação do Python: intro_py\instala.md
  - Primeiros Passos com o Python: intro_py\intro_py.md
  - Programação Científica com o Python:
      - numpy: cientif_py\numpy.md
      - scipy: cientif_py\scipy.md
      - matplotlib: cientif_py\plt.md
      - Jupyter notebooks: cientif_py\jupyter_intro.ipynb
  - Manipulação de dados:
      - pandas: dados_py/pandas.md
  - Dados geoespaciais:
    - Geopandas: geo_py/geopandas.md
  - Referências: ref/ref.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter


extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/255ribeiro
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
      - icon: fontawesome/solid/envelope-square
        link: mailto:ffribeiro@gmail.com